### ISSUE TITLE
Hot Reload Not Firing on Included Shaders

### ISSUE THREAD

**Issue by ryandurkoske** [UstymUkhman/vite-plugin-glsl#12]
Hey its me again!  Not a bug, but an important missing feature.  A change to an included shader doesn't update the including shader, therefore never firing hot reload.

I don't know much about plugin development, but hopefully thats possible.  The best solution would be the included shaders keep track of their parent and you work the changes downward.  Hopefully thats possible, I'd assume it is.

Would you like me to fork and pull request?  I'm writing a pretty large web game/game engine so good GLSL support is vital to me. I can add minification (if it doesn't exist), the recursive hot reloading, and the multi-shader support.  This is your project though, if you're able to get those features added soon and are looking forward to adding them I can stay out of your way.  When can you get these features added by?

**Comment by UstymUkhman** [comment]
Hi! Yes, the Hor Reloading is one feature that's definitely missing here. I'm not quite sure that's possible with shader files, but I haven't made that much research to be honest.

A while ago I've also started developing my own game and I needed a plugin like this to manage my shades. Now it's doing a pretty decent work for me so I prefer now to focus on other pet projects, but I agree with you that there's room for improvements here. So long story short, I'll be happy if you could take a look about adding these features an create PRs whenever you succeed at implementing a stable feature. Thanks a lot and good luck! 🙂

**Comment by UstymUkhman** [comment]
I'm closing this one since I've added minification & warning options (multi-shader support) mentioned above. One thing that's left is the "hot reloading" improvement for which there's a dedicated issue #19. Feel free to open new issues for any unmentioned improvement, thanks!
