### ISSUE TITLE
Could it support custom compression ?

### ISSUE THREAD

**Issue by ziiip** [UstymUkhman/vite-plugin-glsl#23]
Just like [vite-plugin-string](https://github.com/aweikalee/vite-plugin-string) did?

**Comment by UstymUkhman** [comment]
Hi @ziiip and thanks for opening this issue. Yeah, I guess it would be pretty easy to implement. I can work on this when I'll have some time for this update. It's not a bad idea to use a custom compress function as an option, but can I ask you what have you found wrong with the [current compress](https://github.com/UstymUkhman/vite-plugin-glsl/blob/main/src/loadShader.js#L184-L214) implementation?

I mean, I've test it quite a lot and if there's an issue with how it works, I would much prefer fixing it before updating the compress option to use a custom algorithm. Thanks again for your feedback and please consider ⭐ing this plugin if you've found it any useful for your purposes.

**Comment by ziiip** [comment]
It worth ⭐, I just forget it.

Actually, I was using Webpack in previous project, and [webpack-glsl-minify](https://github.com/leosingleton/webpack-glsl-minify)'s minifying seems to be more suitable for me, like c or c++ style  comments removing, name mangling (not using it yet). [preprocessPass1](https://github.com/leosingleton/webpack-glsl-minify/blob/0320a078c4728d3232b81bb5c06294abfaac3b8a/src/minify.ts#L457) and [preprocessPass2](https://github.com/leosingleton/webpack-glsl-minify/blob/0320a078c4728d3232b81bb5c06294abfaac3b8a/src/minify.ts#L501) are the main minifying code.

This plugin is really useful, especially with Three.js, and I think it could be better with a little enhancement in minifying. 

Thanks for the consideration.

**Comment by UstymUkhman** [comment]
Thank you for the explanation and for using it. That totally makes sense. I will add that option, just can't tell you exactly when (maybe this weekend..?) 🙂

**Comment by ziiip** [comment]
As you wish. I am glad that you are going to work on it.
Since I am trapped by many things these days, or I will make a PR with that.

Should I close this issue now, or leave it util you finished?

**Comment by UstymUkhman** [comment]
Naah, I'll close it once I'll publish a new version on NPM.

**Comment by UstymUkhman** [comment]
Closing this since `v0.5.4` was published with an option to use a custom compress callback.
