### ISSUE TITLE
too restrictive `"engines"`

### ISSUE THREAD

**Issue by abernier** [UstymUkhman/vite-plugin-glsl#25]
I think your `package.json` is a bit too restrictive about engines: I get warnings whereas it seems to work just fine with my version of node/npm.

Maybe you could make it a bit more loose?

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vite-plugin-glsl@1.0.0',
npm WARN EBADENGINE   required: { node: '>= 18.12.1', npm: '>= 9.2.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.0', npm: '8.19.2' }
npm WARN EBADENGINE }
```

**Comment by UstymUkhman** [comment]
Oops.., seems like I've made these changes in the wrong repo. 😅
Just published a [new NPM](https://www.npmjs.com/package/vite-plugin-glsl/v/1.0.1) version, thanks!
