### ISSUE TITLE
`#version 300 es` comment gets removed

### ISSUE THREAD

**Issue by luehmann** [UstymUkhman/vite-plugin-glsl#27]
With WebGL 2 some GLSL features require the `#version 300 es` comment to be present. Unfortunately `vite-plugin-glsl` removes this comment just as a regular comment.

**Comment by luehmann** [comment]
Never mind I somehow messed things up myself. Sorry

**Comment by UstymUkhman** [comment]
No problem at all, I'm glad you've solved it. :)
