### ISSUE TITLE
If different files reference the same module, an error will be reported

### ISSUE THREAD

**Issue by sqchenxiyuan** [UstymUkhman/vite-plugin-glsl#3]
If different files reference the same module, an error will be reported

A -> B -> C
A -> D -> C

**Comment by UstymUkhman** [comment]
Hi @sqchenxiyuan ! Thanks for opening this issue, but I'm afraid, I need some more info.

Can you please share your files tree hierarchy and the source code of shaders `A`, `B` and `C`? Also it would be nice to see the actual error you're facing.

The only thing I can imagine right now is that if in your shader `C` you're defining some uniform / variable multiple times, it could be a WebGL program error which is expected. Also, there might be some unintentional recursion in chunks imports which might result in some other error and this is totally expected as well.

Unfortunately I can't tell exactly where is the problem without any error message or source code.
Waiting for updates, cheers!

**Comment by UstymUkhman** [comment]
I'm closing this issue since there haven't been updates for 2 months. Feel free to re-open (with a descriptive error message) if something similar will manifest again. Thanks!
