### ISSUE TITLE
[Question] Unexpected identifier

### ISSUE THREAD

**Issue by tmot24** [UstymUkhman/vite-plugin-glsl#35]
Hello, I use React and Vite. How can I import Shader from file?
In my real project I catch
```
SyntaxError: Unexpected identifier 'highp'
```
In sandbox I catch
```
[plugin:vite:import-analysis] Failed to resolve import "vertex.glsl"
```
Sandbox: https://codesandbox.io/p/sandbox/vite-plugin-glsl-pzy8im

**Comment by UstymUkhman** [comment]
Hi @tmot24 , thanks for using this plugin and for creating a reproducible demo. Can you give me a permission to play around with it? I want to try a couple things. Since I cannot edit it, for now, my best guess is that you need to use `vertexSource` and `fragmentSource` to use shaders as strings as described [here](https://doc.babylonjs.com/features/featuresDeepDive/materials/shaders/shaderMaterial). I saw you've commented that options, so you've probably tried that one, I just want to see the error by myself, thanks!

**Comment by tmot24** [comment]
> Hi @tmot24 , thanks for using this plugin and for creating a reproducible demo. Can you give me a permission to play around with it? I want to try a couple things. Since I cannot edit it, for now, my best guess is that you need to use `vertexSource` and `fragmentSource` to use shaders as strings as described [here](https://doc.babylonjs.com/features/featuresDeepDive/materials/shaders/shaderMaterial). I saw you've commented that options, so you've probably tried that one, I just want to see the error by myself, thanks!

I can't give edit permission via email, can you fork ?
![image](https://user-images.githubusercontent.com/60540588/221594697-95c366cb-5cad-4157-b785-24e4acca590a.png)

**Comment by UstymUkhman** [comment]
@tmot24 

Yeah, sorry, I'm not familiar with codesandbox. 😅
Anyway.., I see it working as expected.., or am I missing something here..?

[My Fork](https://codesandbox.io/p/sandbox/vite-plugin-glsl-forked-ybcvt3?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A27%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A27%2C%22startLineNumber%22%3A7%7D%5D)

**Comment by tmot24** [comment]
@UstymUkhman 

Of course! I made a mistake in the import.

In fact, here is a sandbox close to reality in which I catch my mistake
https://codesandbox.io/p/sandbox/storybook-9hvb6z?file=%2Fsrc%2FButton%2FTemplate.tsx
![image](https://user-images.githubusercontent.com/60540588/221626660-c96db1ef-62b9-4b15-b039-b6a546c30eb7.png)

**Comment by UstymUkhman** [comment]
Ok, now I'm pretty sure it's a codesandbox related issue, 'cause for some reason (probably it expects a JavaScript file no matter what is defined in your `vite.config`) it adds an `?import` suffix to the glsl files. You can check it in the network tab. `vertext` and `fragment` chunks are expected to be JavaScript modules. You can import them like this (raw string) to see your demo working:

```
import vertex from "./vertex.glsl?raw";
import fragment from "./fragment.glsl?raw";
```

Are you able to reproduce the same issue on your localhost? But before that, please remember to install `vite-plugin-glsl` under `devDependencies`  and use `"type": "module"` in your `package.json`.

**Comment by tmot24** [comment]
Yes, you're right, I didn't even know about raw syntax. This is a storybook setup error

**Comment by tmot24** [comment]
Thank you!
