### ISSUE TITLE
Error while importing shader

### ISSUE THREAD

**Issue by Fqlox** [UstymUkhman/vite-plugin-glsl#39]
i wanted to make a shaders using dependencies 

```
#pragma glslify: noise = require(glsl-noise/simplex/2d)

void main() {
  float brightness = noise(gl_FragCoord.xy);

  gl_FragColor = vec4(vec3(brightness), 1.);
}
```

I did install the noise required by npm 

and got in browser console : 

```
webgl-utils.js:66 *** Error compiling shader '[object WebGLShader]':WARNING: 0:1: 'glslify' : unrecognized pragma
ERROR: 0:4: '' : No precision specified for (float)
ERROR: 0:4: 'noise' : no matching overloaded function found

1: #pragma glslify: noise = require(glsl-noise/simplex/2d)
2: 
3: void main() {
4:   float brightness = noise(gl_FragCoord.xy);
5: 
6:   gl_FragColor = vec4(vec3(brightness), 1.);
7: }
```

It seems it did not compile the shader

**Comment by UstymUkhman** [comment]
Hi @Fqlox! Thanks for using `vite-plugin-glsl` and opening an issue here. Please consider giving a star to tis project if you've found it any useful for your purposes. Unfortunately, `glslify` shaders are not supported out of the box by this plugin. You need to remove their custom `#pragma` directive from shader code or use a different library. Please check [this comment](https://github.com/UstymUkhman/vite-plugin-glsl/issues/28#issuecomment-1356847679) and [this issue](https://github.com/UstymUkhman/vite-plugin-glsl/issues/4) for more detailed explanation, thanks!
