### ISSUE TITLE
glslify support

### ISSUE THREAD

**Issue by woutervanerp** [UstymUkhman/vite-plugin-glsl#4]
Hello fellow tech enthusiast,

Does this plugin also support glslify to compile glslify shader code? 
I get this error in my browser:

```
three.module.js:18758 THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: invalid shaders
VERTEX

WARNING: 0:73: 'glslify' : unrecognized pragma
WARNING: 0:74: 'glslify' : unrecognized pragma
WARNING: 0:75: 'glslify' : unrecognized pragma
```

Have a great day!

**Comment by UstymUkhman** [comment]
Hello @woutervanerp , thanks for your question.

The short answer is no, this plugin is not meant to be used with `glslify`.

However, as far as I'm aware, [glslify](https://github.com/glslify/glslify#exporting-a-glsl-module) can handle shader chunks (and even better, specific functions) out of the box by simply using `export` / `require` keywords.

If that wasn't enough, there's [glslify-import](https://npm.io/package/glslify-import) package that can handle this functionality as well.

Cheers!
