### ISSUE TITLE
Tips for making this work with GLSL Lint

### ISSUE THREAD

**Issue by Swoorup** [UstymUkhman/vite-plugin-glsl#43]
I have found that you can make this work with https://marketplace.visualstudio.com/items?itemName=dtoplak.vscode-glsllint

Just use the following script replacing the `script_to_run` to path to glslangValidator. Only downside is that all errors are printed 2 lines below.

```bash
#!/bin/bash

# The script you want to forward the arguments to
script_to_run="/opt/homebrew/bin/glslangValidator"

# Generate a filename based on the current timestamp
timestamp=$(date +%Y%m%d%H%M%S)
log_file="/tmp/glslangValidator_log.txt"

# Log the input arguments
echo "[$timestamp] Input arguments: $@" > "$log_file"

# Concatenate the specified lines to the standard input
echo -e "#version 100\n#extension GL_GOOGLE_include_directive : require\n$(cat)" | "$script_to_run" "$@" 
```

**Comment by UstymUkhman** [comment]
Hi @Swoorup ! Sorry, what do you mean by "making this work"? I use [Shader languages support for VS Code](https://marketplace.visualstudio.com/items?itemName=slevesque.shader) extension for example and as you can see, it's linting correctly my shader files:

![linting](https://github.com/UstymUkhman/vite-plugin-glsl/assets/9247261/1e030079-9625-4b78-95a7-cc6f7cfc8a17)

**Comment by Swoorup** [comment]
> Hi @Swoorup ! Sorry, what do you mean by "making this work"? I use [Shader languages support for VS Code](https://marketplace.visualstudio.com/items?itemName=slevesque.shader) extension for example and as you can see, it's linting correctly my shader files:
> 
> ![linting](https://user-images.githubusercontent.com/9247261/257193007-1e030079-9625-4b78-95a7-cc6f7cfc8a17.png)

Yeah not a question. Just a tip to using the extension I linked. Afaik that extension only supports hlsl linting/validation? The one I linked uses `glslLangValidator` 

<img width="747" alt="image" src="https://github.com/UstymUkhman/vite-plugin-glsl/assets/3408009/c3a2066f-d591-4e74-8036-449db2782522">

**Comment by UstymUkhman** [comment]
Got it, thanks! I would say, if you have a chance to chose, I would go with "Shader languages support for VS Code" since from what I see on the marketplace, their readme claims this extension should work with `HLSL`, `GLSL` and `Cg` shaders and I haven't had any problems using it with WebGL. However, you might consider installing [WGSL](https://marketplace.visualstudio.com/items?itemName=PolyMeilex.wgsl) if you need to work with WebGPU. I haven't tested it deeply myself though.
