### ISSUE TITLE
A question about quotes around nested include file names

### ISSUE THREAD

**Issue by JeffreyPalmer** [UstymUkhman/vite-plugin-glsl#5]
Hi! Thanks for creating this plugin - it was just what I needed. Well, almost, which is why I'm creating this issue.

I was recently building a WegGL application using vite and needed this exact functionality, but when I attempted to use this plugin it was unable to process nested includes from other GLSL files if they used quotes around the filename. Specifically, I was using [Lygia](https://github.com/patriciogonzalezvivo/lygia), but I think that `#include "filename"` is expected to work more generally (?). So, I edited your library to support optional quotation marks around file names and that seems to have done the trick.

As a result, I wanted to see:

- If it was a conscious design decision to not handle quotes around file names. From what I can see in other libraries, this seems expected (see [here](https://github.com/grieve/webpack-glsl-loader/blob/master/index.js#L9), for example).
- If not, would you be interested in a PR that adds that functionality?

Thanks!

**Comment by UstymUkhman** [comment]
Hi @JeffreyPalmer! Thank you so much for opening this issue, you're totally right: the missing support of optional quotation marks around file names is totally a flaw, I actually never thought about this when creating this plugin, so the short answer is no: it was not a conscious design decision to not handle quotes around file names. Thanks for pointing that out!

I have to admit, I'm not an expert in Regular Expressions, so this took me awhile, but eventually it seems I got this working: this is the missing line:

`chunkPath = chunkPath.trim().replace(/^(?:"|')?|(?:"|')?$/gi, '');`

that goes after [this one](https://github.com/UstymUkhman/vite-plugin-glsl/blob/main/src/loadShaders.ts#L48).

I made a few tests and looks like it works with double quotes (`"`), single quotes (`'`) and no quotes (like before) around the file names. Probably this is not the best solution so any advice from your side will be much appreciated!

And if you're wondering if I'm eventually going to support these (`) quotes, the answer is no, and this time it's really a "conscious design decision" 😄.

Thanks again for your support and have a nice day.
Cheers!

P.S.: I'm going to update this plugin on **NPM** asap, probably later today.

**Comment by UstymUkhman** [comment]
Hi @JeffreyPalmer! I'm closing this issue since I've updated this package to handle optional quotation marks around file names starting from [Release #4](https://github.com/UstymUkhman/vite-plugin-glsl/releases/tag/v0.0.7).

Thanks again for your support!

**Comment by JeffreyPalmer** [comment]
Thanks for fixing this so quickly! 🙏
