### ISSUE TITLE
I facing an issue while using a package which uses .glsl files (sheryjs)

### ISSUE THREAD

**Issue by X-sena-X** [UstymUkhman/vite-plugin-glsl#50]
when after using glsl plugin in the vite.config.js. I am still getting this error  

No loader is configured for ".glsl" files: node_modules/sheryjs/src/shaders/effect4/vertex.glsl

    node_modules/sheryjs/src/Effects.js:9:21:
      9 │ import vertex_4 from './shaders/effect4/vertex.glsl'

No loader is configured for ".glsl" files: node_modules/sheryjs/src/shaders/effect2/vertex.glsl

    node_modules/sheryjs/src/Effects.js:5:21:
      5 │ import vertex_2 from './shaders/effect2/vertex.glsl'

vite.config.ts

import { defineConfig } from "vite";
import glsl from "vite-plugin-glsl";
import react from "@vitejs/plugin-react-swc";
import path from "path";
// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react(), glsl()],

    resolve: {
        alias: {
            "@": path.resolve(__dirname, "./src"),
        },
    },
});

package.json

import { defineConfig } from "vite";
import glsl from "vite-plugin-glsl";
import react from "@vitejs/plugin-react-swc";
import path from "path";

export default defineConfig({
    plugins: [react(), glsl()],

    resolve: {
        alias: {
            "@": path.resolve(__dirname, "./src"),
        },
    },
});

can you please assist me in this.

**Comment by UstymUkhman** [comment]
Hi @X-sena-X! Thanks for for using this plugin and opening an issue, I guess it seems pretty similar to #18 and #20. Please check if specifying `optimizeDeps.exclude` config option will fix you problem as described there. You also need to use `"type": "module"` in your `package.json`.

Let me know if this helps, otherwise a minimal reproducible repo would be much appreciated.
Cheers!

**Comment by UstymUkhman** [comment]
Hi @X-sena-X. Any news about this? Did `optimizeDeps.exclude` worked for you?

**Comment by X-sena-X** [comment]
Hi @UstymUkhman , thanks for quick reply. The above solution worked perfectly for me. Thanks for giving me a way out.
