### ISSUE TITLE
compact goes wrong with this code

### ISSUE THREAD

**Issue by basdp** [UstymUkhman/vite-plugin-glsl#53]
I have this function, but compact won't play nice:
```
float scaleLogarithmically(float value, float linMin, float linMax, float logMin, float logMax, float scaleOffset) {
    float x = value;
    float x0 = linMin;
    float x1 = linMax;
    float y0 = logMin + scaleOffset;
    float y1 = logMax + scaleOffset;
    return 
       pow(10.,
            ((x - x0) / (x1 - x0)) * (log10(y1) - log10(y0)) + log10(y0)
        ) - scaleOffset;
}
```
It converts the `return\n      pow(` sequence into `returnpow(`.

**Comment by UstymUkhman** [comment]
Yeah.., you can't have code like that even in JavaScript, to my knowledge, because of the way it automatically inserts semicolons. I'm sorry, but even if theoretically, there's a way to fix it, I don't think it's worth it. Just put `pow(10.,` on the same line of that `return` statement. 🙂

**Comment by basdp** [comment]
Yeah it's not a big issue because it's easily fixed by putting it on the same line, but my GLSL formatter keeps doing it like this. It is valid GLSL by the way, as in GLSL semicolons are not optional :-)

**Comment by UstymUkhman** [comment]
I will take a look at this before the next release of this plugin along side with other possible improvements. 😉 Thanks for using this plugin, btw!

**Comment by UstymUkhman** [comment]
Closing this since it's fixed [here](https://github.com/UstymUkhman/vite-plugin-glsl/commit/9e700625807cd92a8dfe66198d66a7bfb3f20b72). Will update on NPM soon.
