### ISSUE TITLE
How to handle #include conflicts (function already has a body)?

### ISSUE THREAD

**Issue by misaelvillaverde** [UstymUkhman/vite-plugin-glsl#57]
Hello, awesome library. I got this on my `vertex.glsl`

```c
#include ../partials/perlin3d;
#include ../partials/perlin4d;

void main() {
    . . .
}
```

The issue is that perlin3d and perlin4d share some functions, how would you handle the conflict?

Should I separate the functions into another file and include it each time I call perlin3d or perlin4d?

Error:
![CleanShot 2024-08-08 at 20 47 17@2x](https://github.com/user-attachments/assets/d50765ca-cafa-43c7-be45-b75dd9108250)

**Comment by UstymUkhman** [comment]
Hi @misaelvillaverde, thanks! And thanks for your star. Yes, you are correct. As explained [here](https://github.com/UstymUkhman/vite-plugin-glsl/issues/28#issuecomment-1356847679), this plugin does not create any scope for variables or functions defined within one chuck. So basically, you should rename at least one of those functions to avoid naming conflicts.
