### ISSUE TITLE
如何关闭去除代码中的注释行为，我需要用注释进行定位并替换代码

### ISSUE THREAD

**Issue by 3261564019** [UstymUkhman/vite-plugin-glsl#58]
例如：
`
uniform float uTime;
//logdepthbuf_pars_fragment
void main() {
}
`
`let v=vertex.replace("//logdepthbuf_pars_vertex",ShaderChunk.logdepthbuf_pars_vertex)`

引入的.glsl文件中不存在 `//logdepthbuf_pars_fragment` 因此我无法完成替换

**Comment by UstymUkhman** [comment]
你好！我懂了。
在版本 1.3.0 中，我新增了一個選項，用於在使用三斜線 (`///`) 時保留著色器註解。您可以嘗試一下，看看它是否可以實現您想要實現的目標嗎？

您也可以根據需要使用組態選項中的 `compress` 函數來取代這些註解。當所有著色器區塊都被引入並合併時，它會作為最後一步運行。
讓我知道這是否有效。乾杯！

**Comment by 3261564019** [comment]
> 你好！我懂了。 在版本 1.3.0 中，我新增了一個選項，用於在使用三斜線 (`///`) 時保留著色器註解。您可以嘗試一下，看看它是否可以實現您想要實現的目標嗎？
> 
> 您也可以根據需要使用組態選項中的 `compress` 函數來取代這些註解。當所有著色器區塊都被引入並合併時，它會作為最後一步運行。 讓我知道這是否有效。乾杯！

很好的设计，这是有用的，谢谢你的回复！很好的插件

**Comment by UstymUkhman** [comment]
謝謝，我很感激！🙂  如果您發現它有用，請隨時給它一顆星。
