### ISSUE TITLE
Doesn't seem to process nested #include statements without semicolon

### ISSUE THREAD

**Issue by cmalven** [UstymUkhman/vite-plugin-glsl#6]
I've been attempting to use this plugin to include files from https://github.com/patriciogonzalezvivo/lygia and it seems that `vite-plugin-glsl` doesn't process any `#include` statements in nested files unless they end with a `;`

As an example:

```glsl
// in main.frag

// this works
#include "lygia/draw/circle.glsl";
```

```glsl
// in lygia/draw/circle.glsl

// All three of these fail to be processed because they don't end with a semicolon
#include "../sdf/circleSDF.glsl"
#include "fill.glsl"
#include "stroke.glsl"

...
```

Given that lygia works with most other standard GLSL implementations that support `#include`, I would assume that the semicolon isn't actually required. Could `vite-plugin-glsl` be updated to remove the requirement for a semicolon at the end of these statements?

Thank you for your work on this plugin!

**Comment by UstymUkhman** [comment]
Hi Chris!

Thank you for opening this issue. Yes, it's totally possible to mark semicolons at the end of `#include` statements as optional. I will update this plugin and it's version on NPM in a next few days. I'll close this issue after the publication. Please consider ⭐ing this package if you like it.

Thanks again and have nice day.
Cheers!

**Comment by cmalven** [comment]
@UstymUkhman Thanks for your quick response and I look forward to this being fixed. I've tried soooo many rollup + vite plugins trying to get `#include` working reliably with Vite and this plugin is the closest I've come so far. Really appreciate what you're doing. Starred!

**Comment by UstymUkhman** [comment]
I've updated this plugin to [`v0.0.9`](https://github.com/UstymUkhman/vite-plugin-glsl/releases/tag/v0.0.9). I hope now it's fully compatible with *lygia* files. Please feel free to open another issue in case you notice something wrong with this update or think about any other improvement. Thanks again for your feedback. I really appreciate it. Cheers!
